reseach_assistant_task:
  description: >
    Use the search tool to search the internet using these queries: {queries}. Strictly focus on results from {country}.
    Your goal is to collect research data and grey literature (news articles) on citizen engagements in {country}.
    If no relevant information is found, say so.
    Reference information from accurate and reputable sources.
  expected_output: >
    A list of top 10 Climate Change Engagements in {country} that were reported over the {period}, add correct URLs and title of research items.
    show a count of articles found from search tools.
sector_specialist_task:
  description: >
      Review collected data for relevance to climate change.
      # Identify climate change engagement initiatives from the collected data.
      Map engagements to SDG target 13.3.
      Use only South African data.
      Exclude other African countries except South Africa.
      # You check the correctness of the URLS and the information collected.
      # If no relevant information is found, say so.
      Reference information from accurate and reputable sources.
      Identify the following about climate action from articles: project name, location, description, sdg map, impact, use the structure from {mapping_structure} to structure output:
      {mapping_structure}
  expected_output: >
      # A screened and evaluated list of citizen engagements in {country}.
      # A list of URL validity checks performed, use words like valid for valid links and invalid for invalid links that redirect to 404
      A list of engagements initiatives mapped to SDG target 13.3. using {mapping_structure} structure with correct links or URLS to the actual resource or article.
sdg_specialist_task:
  description: >
    Your tasks are as follows:
    Search: Citizen engagement initiatives in climate action (outside South Africa).
    Extract: Climate change actions from text.
    Research: Articles on mapping SDG 13, target 13 (use "Our World in Data" for clues). 
    Studies on mapping SDG goals through content analysis (outside South Africa, use "Our World in Data" for clues).
    Guidelines:Search about SDG Mapping strategie.
    Provide accurate and reputable sources with links/URLs.
    If no relevant information is found, say so.

  expected_output: >
      A list of extracted articles about mapping SDG goal 13
      The list should also have accurate links or URLS that references the extracted articles.